#pragma once
#include <wx/string.h>
#include <wx/image.h>


/**
 * @brief A container for debugging information generated by a plugin.
 *
 * This class wraps a plugin's unique identifier and a corresponding visual
 * debug image.
 */
class PluginDebugResultView
{
public:
    //-----------------------------------------------------------------------------
    // Constructor/Destructor
    //-----------------------------------------------------------------------------

    /**
     * @brief Constructs a result view with a plugin Id and an image.
     * @param pluginId The unique string identifier of the originating plugin.
     * @param debugImage The wxImage containing visual debug data.
     */
    PluginDebugResultView(
        wxString pluginId,
        wxImage debugImage
    );

    ~PluginDebugResultView() = default;


    //-----------------------------------------------------------------------------
    // Class operators
    //-----------------------------------------------------------------------------

    /** @brief Returns the unique identifier of the plugin that created this result. */
    const wxString& pluginId() const;

    /** @brief Returns a reference to the debug image. */
    const wxImage& debugImage() const;

private:
    // The originating plugin's Id.
    wxString pluginId_;

    // The visual debug data.
    wxImage debugImage_;
};