#include "CameraWidgetEvents.hpp"


wxDEFINE_EVENT(GUI_SELECT_CAMERA, wxCommandEvent);

wxDEFINE_EVENT(GUI_RIGHT_CLICK_CAMERA, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHECK_CAMERA, wxCommandEvent);

wxDEFINE_EVENT(GUI_CONNECT_CAMERA, wxCommandEvent);

wxDEFINE_EVENT(GUI_DISCONNECT_CAMERA, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHANGE_BEHAVIOUR, wxCommandEvent);