#include "CameraAssistantViewEvents.hpp"


wxDEFINE_EVENT(GUI_CAM_ASSIST_LOAD_SETTINGS, wxCommandEvent);

wxDEFINE_EVENT(GUI_CAM_ASSIST_SAVE_SETTINGS, wxCommandEvent);

wxDEFINE_EVENT(GUI_CAM_ASSIST_SAVE_SETTINGS_AS, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHANGE_DISCOVERY_BEHAVIOUR, wxCommandEvent);

wxDEFINE_EVENT(GUI_LOAD_CAMERAS_FILE, wxCommandEvent);

wxDEFINE_EVENT(GUI_AUTO_DISCOVERY, wxCommandEvent);

wxDEFINE_EVENT(GUI_DISCOVER_INTERFACE, wxCommandEvent);

wxDEFINE_EVENT(GUI_SAVE_CAMERAS_FILE, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHANGE_CATEGORY, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHANGE_VISIBILITY, wxCommandEvent);

wxDEFINE_EVENT(GUI_CHANGE_PARAMS_PERSISTENCE, wxCommandEvent);
