#include "SetupPageEvents.hpp"


wxDEFINE_EVENT(GUI_SETUP_LOAD_CONFIG, wxCommandEvent);
wxDEFINE_EVENT(GUI_SETUP_SAVE_CONFIG, wxCommandEvent);
wxDEFINE_EVENT(GUI_SETUP_LOAD_MODEL_PARAMS, wxCommandEvent);
wxDEFINE_EVENT(GUI_SETUP_SAVE_MODEL_PARAMS, wxCommandEvent);
wxDEFINE_EVENT(GUI_AUTOMATIC_MODE, wxCommandEvent);
wxDEFINE_EVENT(GUI_FROM_HARDWARE_MODE, wxCommandEvent);
wxDEFINE_EVENT(GUI_FREE_MODE, wxCommandEvent);