#pragma once
#include <vector>
#include <memory>
#include "EvaluationDefs.hpp"
#include "PluginResult.hpp"


/**
 * @brief Container that associates a source object with its diagnostic assessments.
 * 
 * This class is designed to be immutable once constructed. It holds the original
 * object and a collection of plugin results, providing an aggregated status based
 * on those results.
 * 
 * @tparam T The type of the object that was evaluated.
 */
template<typename T>
class EvaluationResult
{
public:
    //-----------------------------------------------------------------------------
    // Enums and structs
    //-----------------------------------------------------------------------------

    /**
     * @brief Represents the high-level outcome of the evaluation process.
     */
    enum class Status {
        NOT_EVALUATED,      ///< No plugins have processed this object yet.
        GOOD,               ///< All assessments passed without issues.
        HAS_ISSUES          ///< At least one assessment reported a problem.
    };


    //-----------------------------------------------------------------------------
    // Constructor/Destructor
    //-----------------------------------------------------------------------------

    /**
     * @brief Constructs an evaluation result.
     * @param object The source data object being evaluated.
     * @param assessments A vector of shared pointers to results generated by plugins.
     */
    EvaluationResult(
        const T& object,
        const std::vector<std::shared_ptr<PluginResult>>& assessments = {}
    );

    ~EvaluationResult() = default;


    //-----------------------------------------------------------------------------
    // Class operators
    //-----------------------------------------------------------------------------

    /** @brief Returns a reference to the evaluated object. */
    const T& object() const;

    /** @brief Returns the list of individual plugin results. */
    const std::vector<std::shared_ptr<PluginResult>>& assessments() const;

    /** @brief Returns the aggregated status of this evaluation. */
    Status status() const;

private:
    void init();

private:
    // The data object under evaluation.
    T object_;

    // Collection of diagnostic results.
    std::vector<std::shared_ptr<PluginResult>> assessments_;

    // The computed overall status.
    Status status_;
};

#include "EvaluationResult.inl"
